### ISSUE TITLE
ImportError: No module named 'tensorflow.python.distribute.cross_device_ops'

### ISSUE THREAD

**Issue by LeoWood** [HaoyuHu/bert-multi-gpu#11]
When I ran the script run_custom_classifier.py, the error occured:
ImportError: No module named 'tensorflow.python.distribute.cross_device_ops'

python: 3.5.2
tensorflow-gpu: 1.11.0
ubuntu 16.04

How can I handle this?
Thanks

**Comment by LeoWood** [comment]
![image](https://user-images.githubusercontent.com/17940401/65041822-27535e00-d98a-11e9-9529-1a5cebfef7ed.png)

**Comment by LeoWood** [comment]
![image](https://user-images.githubusercontent.com/17940401/65041878-4d78fe00-d98a-11e9-8839-b19794ddc7d9.png)

**Comment by haoyuhu** [comment]
Please try upgrading TensorFlow to 1.14.

**Comment by shishishu** [comment]
> Please try upgrading TensorFlow to 1.14.

Yep, it succeed with this suggestions. Thanks Haha.

**Comment by bigzhouj** [comment]
Tensorflow version 1.15does not work，only 1.14?

**Comment by haoyuhu** [comment]
> Tensorflow version 1.15does not work，only 1.14?

TF verison above 1.14 is ok.
