### ISSUE TITLE
AttributeError: 'list' object has no attribute 'text_a'

### ISSUE THREAD

**Issue by gr8Adakron** [HaoyuHu/bert-multi-gpu#13]
I got this error while training using multi-GPU. I am getting good accuracy ~90% with BERT of single GPU, and now I am train the model using multi-GPU with extra data but getting this error:
```


I0927 12:31:52.653539 140638168917760 run_custom_classifier.py:1006]   Num examples = 2400
I0927 12:31:52.654157 140638168917760 run_custom_classifier.py:1007]   Batch size = 32
I0927 12:31:52.654301 140638168917760 run_custom_classifier.py:1008]   Num steps = 75
W0927 12:31:52.654463 140638168917760 deprecation_wrapper.py:119] From run_custom_classifier.py:580: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

I0927 12:31:52.661087 140638168917760 estimator.py:360] Skipping training since max_steps has already saved.
I0927 12:31:52.668826 140638168917760 run_custom_classifier.py:552] Writing example 0 of 2
Writing example 0 of 2
Traceback (most recent call last):
  File "run_custom_classifier.py", line 1139, in <module>
    tf.app.run()
  File "/home/serving/.virtualenvs/bert_env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/serving/.virtualenvs/bert_env/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/serving/.virtualenvs/bert_env/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_custom_classifier.py", line 1078, in main
    predict_file)
  File "run_custom_classifier.py", line 556, in file_based_convert_examples_to_features
    max_seq_length, tokenizer)
  File "run_custom_classifier.py", line 458, in convert_single_example
    tokens_a = tokenizer.tokenize(example.text_a)
AttributeError: 'list' object has no attribute 'text_a'


```

This my training sample:

```
item_id            word_phrase                                                          value
445095147       Labrada Nutrition Charge Supershot - 2.5 fl oz - (Pack of 6)    Energy Drinks
```

Is it because my columns names are different? do I have to change it somewhere?

Help is appreciated.

**Comment by haoyuhu** [comment]
> AttributeError: 'list' object has no attribute 'text_a'

If you define your own task data processor by implementing `DataProcessor` class, make sure that the return value of `_create_examples(self, lines, set_type)` is a list of [`InputExample`](https://github.com/HaoyuHu/bert-multi-gpu/blob/089515689f44b6f3e30a1bdae2476336d325942c/run_custom_classifier.py#L145).

**Comment by gr8Adakron** [comment]
@HaoyuHu 
thanks alot it helped, and another thing why does it take to read the data, I mean compare to basic bert_algo(run_classifier.py)- this multi gpu script increases the time complexity by 10-20x to read the data from train.tsv

is it anything i can do to fasten that speed?

**Comment by haoyuhu** [comment]
It's weird. The code for data processing is almost the same as the original code(run_classifier.py). You can compare the code differences. If there is anything wrong, pls let me know. Many thanks.
