### ISSUE TITLE
No OpKernel was registered to support Op 'NcclAllReduce' used by node NcclAllReduce

### ISSUE THREAD

**Issue by qiu-nian** [HaoyuHu/bert-multi-gpu#15]
您好，我在使用的时候报下面的错误:
No OpKernel was registered to support Op 'NcclAllReduce' used by node NcclAllReduce（）with these attrs:[shared_name=c0,T=DT_FLOAT,num_devices=4,reduction="sum]
您知道是为什么吗，我猜想是不是NCCL没有安装的问题，但是同事用Mxnet是可以多卡训练的，然后也不知道怎么检测服务器上的NCCL的安装情况，所以不知道您是否知道上面的报错是什么原因？

望解答，多谢！

**Comment by haoyuhu** [comment]
这个问题我也遇到过，确实是nccl安装的问题。可以使用`hierarchical_copy`，替换后应该可以正常训练。
REF1: https://github.com/HaoyuHu/bert-multi-gpu/blob/master/run_custom_classifier.py#L927
REF2: https://github.com/tensorflow/tensorflow/issues/21470#issuecomment-422506263

**Comment by qiu-nian** [comment]
> 这个问题我也遇到过，确实是nccl安装的问题。可以使用`hierarchical_copy`，替换后应该可以正常训练。
> REF1: https://github.com/HaoyuHu/bert-multi-gpu/blob/master/run_custom_classifier.py#L927
> REF2: [tensorflow/tensorflow#21470 (comment)](https://github.com/tensorflow/tensorflow/issues/21470#issuecomment-422506263)

谢谢你的解答！！这样设置之后，模型训练用的是CPU

**Comment by haoyuhu** [comment]
训练应该是用的GPU。
REF: https://www.tensorflow.org/api_docs/python/tf/distribute/HierarchicalCopyAllReduce
> It reduces to one GPU along edges in some hierarchy and broadcasts back to each GPU along the same path. Before performing all-reduce, tensors will be repacked or aggregated for more efficient cross-device transportation.
> This is a reduction created for Nvidia DGX-1 which assumes GPUs connects like that on DGX-1 machine. If you have different GPU inter-connections, it is likely that it would be slower than `tf.distribute.ReductionToOneDevice`.

**Comment by qiu-nian** [comment]
当时跑的时候，因为速度特别慢，所以我看了下GPU的使用率，当时用了四块卡，但是每块卡的使用率为0%。然后再看了下CPU的使用率，超过100%了，可能还是得用nccl这个才能解决问题，tensorflow真的是用得太虐了。。。。。。。

**Comment by haoyuhu** [comment]
> 当时跑的时候，因为速度特别慢，所以我看了下GPU的使用率，当时用了四块卡，但是每块卡的使用率为0%。然后再看了下CPU的使用率，超过100%了，可能还是得用nccl这个才能解决问题，tensorflow真的是用得太虐了。。。。。。。

可以试试pytorch:)
