### ISSUE TITLE
can I use it for multi gpu prediction?

### ISSUE THREAD

**Issue by TPF2017** [HaoyuHu/bert-multi-gpu#21]
can I use it for multi gpu prediction? there are only train_distribute and eval_distribute parameters in tf.estimator.RunConfig

**Comment by haoyuhu** [comment]
@TPF2017 
Yes, you can use Multi-GPU for prediction. Pls update your code. 
Related PR: https://github.com/HaoyuHu/bert-multi-gpu/pull/22.
```
...
--use_gpu=true \
--num_gpu_cores=2 \
--do_train=false \
--do_eval=true \
--do_predict=true
```

**Comment by TPF2017** [comment]
so, how you make it possible for using distributed strategy in PREDICTION mode. I still don't know what you have done after reading your code, can you tell it in detail? thanks a lot!

**Comment by haoyuhu** [comment]
> so, how you make it possible for using distributed strategy in PREDICTION mode. I still don't know what you have done after reading your code, can you tell it in detail? thanks a lot!

Actually, according to the guide of Tensorflow, `tf.distribute.MirroredStrategy` can be used for distributing evaluation and prediction on different platforms. But I haven't tried, so I don't know it really works or not.
REF: https://www.tensorflow.org/guide/distributed_training
> `tf.distribute.Strategy` intends to support both these modes of execution. Although we discuss training most of the time in this guide, **this API can also be used for distributing evaluation and prediction on different platforms.**

In addition, you can do it manually.
* Divide data into K parts.
* Start entry script with environment variable CUDA_VISIBLE_DEVICES(from 0 to K), then in every python process only ONE GPU is visible.

**Comment by TPF2017** [comment]
I have run your code for multi-gpu prediction, and it really work, but I just can't find out which line is important, I have written a code that really similar to yous that can only use multi-gpu for Train and Evaluate, can you tell me what you have done here?

**Comment by haoyuhu** [comment]
Does it raise an error when you run your prediction code? Or, it is able to complete the entire predictions but only using single-core GPU?

Some important lines:
* https://github.com/HaoyuHu/bert-multi-gpu/blob/master/run_custom_classifier.py#L781
* https://github.com/HaoyuHu/bert-multi-gpu/blob/master/run_custom_classifier.py#L932
* https://github.com/HaoyuHu/bert-multi-gpu/blob/master/run_custom_classifier.py#L981

**Comment by TPF2017** [comment]
Yes, it is able to complete the entire predictions but only using single-core GPU, and I have checked the above lines in the code, but have not found any difference.

**Comment by haoyuhu** [comment]
Could you pls provide a piece of code and related test dataset to reproduce this bug?

**Comment by TPF2017** [comment]
I cannot copy my code from the company computer, I'll  try to rewrite my code based on your code, thanks for your reply.
