### ISSUE TITLE
run_pretraining.py script for multi-gpu

### ISSUE THREAD

**Issue by ftamburin** [HaoyuHu/bert-multi-gpu#23]
Hi. Very nice project! Is there a code equivalent to the original "run_pretraining.py" for pre-training BERT from scratch using new texts and your bert-multi-gpu code?
Thanks.

**Comment by haoyuhu** [comment]
Sorry, there is currently no such plan. Maybe I will release multi-GPU version for pre-training in the future.
BTW: This [project](https://github.com/guotong1988/BERT-multi-gpu) may help you.
