### ISSUE TITLE
能否使用多GPU进行evaluate？

### ISSUE THREAD

**Issue by ZZKa** [HaoyuHu/bert-multi-gpu#29]
我看代码中 evaluate的时候，换成了单GPU的estimator，请问能否使用多GPU进行评估呢？如果我要在多GPU使用train_and_evaluate，可以实现吗？

**Comment by haoyuhu** [comment]
印象中tf的几个metrics不支持multi-gpu，所以EVAL阶段换成了单GPU。如果你不需要precision、recall、f1，可以尝试注释这段并修改代码支持multi-gpu。
https://github.com/HaoyuHu/bert-multi-gpu/blob/master/run_custom_classifier.py#L758
