### ISSUE TITLE
Question: Does it make sense to integrate tensorflow2?

### ISSUE THREAD

**Issue by AndreasFdev** [HaoyuHu/bert-multi-gpu#3]
Hey,
Thanks alot for the multi-gpu-support.
Since limited cash I've to work with 8GB GPU's for study.

Right now I wounder, if upgrading to tensorflow 2.0 would have any benefit.

Best regards
Andreas

**Comment by haoyuhu** [comment]
I don't think it would help much to upgrade to TF2.0. I suggest you try the `bert-base-uncased` model instead of `bert-large-uncased` model.
REF: https://github.com/HaoyuHu/bert-multi-gpu/issues/1#issuecomment-493381661

**Comment by soloice** [comment]
@AndreasFdev TF 2.0 will NOT help. Actually TF 2.0 is incompatible with repo, because it removed many things from `tf.contrib`, on which BERT heavily relies.

**Comment by AndreasFdev** [comment]
> @AndreasFdev TF 2.0 will NOT help. Actually TF 2.0 is incompatible with repo, because it removed many things from `tf.contrib`, on which BERT heavily relies.

soloice, I'm aware about the todo's. That's why I ask for benefits that may be worth the trouble.

**Comment by AndreasFdev** [comment]
HaoyuHu, how do you know that I'm going to check if it is possible to find usefull parameters to survive OOM on `bert-large-uncased` ? ;-)
Thanks for your answer. So for now your version is the best for my needs. Cheers

**Comment by HaoyuHu** [comment]
Enjoy it! @soloice

**Comment by haoyuhu** [comment]
Closing the issue since this is not likely a bug.
