### ISSUE TITLE
支持多gpu预训练么

### ISSUE THREAD

**Issue by joytianya** [HaoyuHu/bert-multi-gpu#30]

**Comment by haoyuhu** [comment]
抱歉，不支持多GPU预训练。

**Comment by joytianya** [comment]
可以支持么？这个多gpu的下游任务的改的方法能直接适用于预训练的代码么？使得可以多gpu预训练么

**Comment by haoyuhu** [comment]
> 可以支持么？这个多gpu的下游任务的改的方法能直接适用于预训练的代码么？使得可以多gpu预训练么

可以参考：https://github.com/guotong1988/BERT-GPU
这个项目可以用于预训练。

**Comment by joytianya** [comment]
十分感谢，我看看
