### ISSUE TITLE
Query regarding calculation of iteration_steps and role of global_batch_size.

### ISSUE THREAD

**Issue by Q-Udita** [HaoyuHu/bert-multi-gpu#32]
I have 100000 observations(num_train_examples ), train_batch_size  = 4, num_gpu_cores  = 8,
I want to train with num_train_epochs = 1,
Could you please suggest do I need to go for
situation -1 iteration_steps  = 100000/32 or
situation -2 iteration_steps = 100000/4 

If I go with situation-2 what is the role of global_batch_size ?

**Comment by shishishu** [comment]
> I have 100000 observations(num_train_examples ), train_batch_size = 4, num_gpu_cores = 8,
> I want to train with num_train_epochs = 1,
> Could you please suggest do I need to go for
> situation -1 iteration_steps = 100000/32 or
> situation -2 iteration_steps = 100000/4
> 
> If I go with situation-2 what is the role of global_batch_size ?

Assume that fixed num_train_epochs = 1 and train_batch_size = 4. If use multi-gpu and num_gpu_cores = 8 (situation 1), then global_batch_size = 32 and iteration step =  100000/4. If num_gpu_cores = 1 only (situation 2), then global_batch_size = 4 and iteration step = 100000/4 also. Now, you can see the difference that situation 1 could provide larger effective batch_size in training (32 vs. 4) with same iteration step and it is more stable.
