### ISSUE TITLE
In prediction, only one gpu is available 

### ISSUE THREAD

**Issue by hys50001** [HaoyuHu/bert-multi-gpu#35]
First, Thanks for your amazing repository.
 
i have some problem.

In train all gpus are used, but in prediction only gpu:0 is used. 

 i saw someone else has raised this issue before. 

thanks

**Comment by haoyuhu** [comment]
Hi! 
You can divide the data into multiple parts, and start your python script with environment variable CUDA_VISIBLE_DEVICES(from 0 to 7), then in every python process only ONE GPU is visible.

**Comment by hys50001** [comment]
thanks
