### ISSUE TITLE
Prediction using Multi-GPU bert

### ISSUE THREAD

**Issue by aswin-giridhar** [HaoyuHu/bert-multi-gpu#7]
Hi,
Thanks a lot for providing the multi-gpu-support for bert.
I am currently working on a bert project which usually takes 30 mins for prediction when using a single gpu. I have 8 gpus and I want to split the data into 8 parts and give one to each gpu. So I want to know if I would be able to run the predictions simultaneously in the 8 GPUS using your bert repo?

Best,
Aswin

**Comment by haoyuhu** [comment]
Sorry for the late reply. using `--do_predict=true` and `--use_gpu=true` and `--num_gpu_cores=8` may work. You can have a try. 
Feel free to open new issue if you are having trouble. Looking forward to your good news.

**Comment by haoyuhu** [comment]
In addition, you can start your python script with environment variable CUDA_VISIBLE_DEVICES(from 0 to 7), then in every python process only ONE GPU is visible.
